#!/usr/bin/env bats
# generate-agent-all-combos.bats -- Tests for all 27 role+dept agent generation combinations
# Plan 08-06: BATS tests for template generation pipeline

setup() {
  load '../test_helper/common'
  GENERATE="$SCRIPTS_DIR/generate-agent.sh"
  ROLES=(architect lead senior dev tester qa qa-code security documenter)
  DEPTS=(backend frontend uiux)
}

# --- Basic generation tests (all 27 combos) ---

@test "generate-agent.sh exits 0 for all 27 combinations" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      run bash "$GENERATE" --role "$role" --dept "$dept" --dry-run
      [ "$status" -eq 0 ] || {
        echo "FAIL: ${dept}/${role} exited with $status"
        return 1
      }
    done
  done
}

@test "generate-agent.sh produces non-empty output for all 27 combinations" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      run bash "$GENERATE" --role "$role" --dept "$dept" --dry-run
      [ -n "$output" ] || {
        echo "FAIL: ${dept}/${role} produced empty output"
        return 1
      }
    done
  done
}

@test "no unreplaced {{PLACEHOLDER}} patterns in any of 27 combinations" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      UNREPLACED=$(echo "$OUTPUT" | grep -oE '\{\{[A-Z_]+\}\}' || true)
      [ -z "$UNREPLACED" ] || {
        echo "FAIL: ${dept}/${role} has unreplaced: $UNREPLACED"
        return 1
      }
    done
  done
}

@test "all 27 combinations contain YAML frontmatter" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      echo "$OUTPUT" | grep -q "^---$" || {
        echo "FAIL: ${dept}/${role} missing YAML frontmatter delimiter"
        return 1
      }
    done
  done
}

@test "all 27 combinations contain expected name field in frontmatter" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      echo "$OUTPUT" | grep -q "^name: yolo-" || {
        echo "FAIL: ${dept}/${role} missing name field"
        return 1
      }
    done
  done
}

@test "all 27 combinations contain H1 heading" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      echo "$OUTPUT" | grep -q "^# YOLO" || {
        echo "FAIL: ${dept}/${role} missing H1 heading"
        return 1
      }
    done
  done
}

# --- No stderr warnings (all 27) ---

@test "no unreplaced placeholder warnings on stderr for any combination" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      STDERR=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>&1 >/dev/null)
      WARNINGS=$(echo "$STDERR" | grep -i "warning\|unreplaced" || true)
      [ -z "$WARNINGS" ] || {
        echo "FAIL: ${dept}/${role} stderr warning: $WARNINGS"
        return 1
      }
    done
  done
}

# --- Dept prefix correctness ---

@test "backend agents have no dept prefix in name field" {
  for role in "${ROLES[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role "$role" --dept backend --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "^name: yolo-${role}$" || {
      echo "FAIL: backend/${role} wrong name field"
      return 1
    }
  done
}

@test "frontend agents have fe- prefix in name field" {
  for role in "${ROLES[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role "$role" --dept frontend --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "^name: yolo-fe-${role}$" || {
      echo "FAIL: frontend/${role} wrong name field"
      return 1
    }
  done
}

@test "uiux agents have ux- prefix in name field" {
  for role in "${ROLES[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role "$role" --dept uiux --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "^name: yolo-ux-${role}$" || {
      echo "FAIL: uiux/${role} wrong name field"
      return 1
    }
  done
}

# --- Validation edge cases ---

@test "invalid role is rejected" {
  run bash "$GENERATE" --role invalid --dept backend --dry-run
  assert_failure
  assert_output --partial "invalid role"
}

@test "invalid dept is rejected" {
  run bash "$GENERATE" --role dev --dept invalid --dry-run
  assert_failure
  assert_output --partial "invalid dept"
}

@test "missing --role is rejected" {
  run bash "$GENERATE" --dept backend --dry-run
  assert_failure
  assert_output --partial "--role is required"
}

@test "missing --dept is rejected" {
  run bash "$GENERATE" --role dev --dry-run
  assert_failure
  assert_output --partial "--dept is required"
}

# --- T2: GENERATED marker tests ---

@test "all 27 combinations contain GENERATED marker" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      echo "$OUTPUT" | grep -q "<!-- GENERATED by generate-agent.sh" || {
        echo "FAIL: ${dept}/${role} missing GENERATED marker"
        return 1
      }
    done
  done
}

@test "GENERATED marker is the first line of output" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      FIRST_LINE=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null | head -1)
      [[ "$FIRST_LINE" == "<!-- GENERATED by generate-agent.sh"* ]] || {
        echo "FAIL: ${dept}/${role} first line: $FIRST_LINE"
        return 1
      }
    done
  done
}

# --- T2: Role-appropriate section tests ---

@test "dev agents contain Execution Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role dev --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Execution Protocol" || {
      echo "FAIL: ${dept}/dev missing Execution Protocol"
      return 1
    }
  done
}

@test "senior agents contain Design Review section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role senior --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Mode 1: Design Review" || {
      echo "FAIL: ${dept}/senior missing Design Review"
      return 1
    }
  done
}

@test "senior agents contain Code Review section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role senior --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Mode 2: Code Review" || {
      echo "FAIL: ${dept}/senior missing Code Review"
      return 1
    }
  done
}

@test "lead agents contain Planning Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role lead --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Planning Protocol" || {
      echo "FAIL: ${dept}/lead missing Planning Protocol"
      return 1
    }
  done
}

@test "architect agents contain Core Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role architect --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Core Protocol" || {
      echo "FAIL: ${dept}/architect missing Core Protocol"
      return 1
    }
  done
}

@test "tester agents contain Test Quality Standards section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role tester --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Test Quality Standards" || {
      echo "FAIL: ${dept}/tester missing Test Quality Standards"
      return 1
    }
  done
}

@test "qa agents contain Verification Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role qa --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Verification Protocol" || {
      echo "FAIL: ${dept}/qa missing Verification Protocol"
      return 1
    }
  done
}

@test "qa-code agents contain Verification Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role qa-code --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Verification Protocol" || {
      echo "FAIL: ${dept}/qa-code missing Verification Protocol"
      return 1
    }
  done
}

@test "security agents contain Audit Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role security --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Audit Protocol" || {
      echo "FAIL: ${dept}/security missing Audit Protocol"
      return 1
    }
  done
}

@test "documenter agents contain Documentation Protocol section" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role documenter --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Documentation Protocol" || {
      echo "FAIL: ${dept}/documenter missing Documentation Protocol"
      return 1
    }
  done
}

# --- T2: Overlay value substitution tests ---

@test "frontend agents contain FE label in hierarchy" {
  OUTPUT=$(bash "$GENERATE" --role dev --dept frontend --dry-run 2>/dev/null)
  echo "$OUTPUT" | grep -q "FE" || {
    echo "FAIL: frontend/dev missing FE label"
    return 1
  }
}

@test "uiux agents contain UX label in output" {
  OUTPUT=$(bash "$GENERATE" --role dev --dept uiux --dry-run 2>/dev/null)
  echo "$OUTPUT" | grep -q "UX" || {
    echo "FAIL: uiux/dev missing UX label"
    return 1
  }
}

@test "frontend dev agent has frontend dept key in test-results schema" {
  OUTPUT=$(bash "$GENERATE" --role dev --dept frontend --dry-run 2>/dev/null)
  echo "$OUTPUT" | grep -q "dept:'frontend'" || {
    echo "FAIL: frontend/dev missing dept:'frontend' in test-results schema"
    return 1
  }
}

@test "uiux dev agent has uiux dept key in test-results schema" {
  OUTPUT=$(bash "$GENERATE" --role dev --dept uiux --dry-run 2>/dev/null)
  echo "$OUTPUT" | grep -q "dept:'uiux'" || {
    echo "FAIL: uiux/dev missing dept:'uiux' in test-results schema"
    return 1
  }
}

@test "backend dev agent has backend dept key in test-results schema" {
  OUTPUT=$(bash "$GENERATE" --role dev --dept backend --dry-run 2>/dev/null)
  echo "$OUTPUT" | grep -q "dept:'backend'" || {
    echo "FAIL: backend/dev missing dept:'backend' in test-results schema"
    return 1
  }
}

@test "all agents have Hierarchy section with correct escalation chain" {
  for dept in "${DEPTS[@]}"; do
    OUTPUT=$(bash "$GENERATE" --role dev --dept "$dept" --dry-run 2>/dev/null)
    echo "$OUTPUT" | grep -q "## Hierarchy" || {
      echo "FAIL: ${dept}/dev missing Hierarchy section"
      return 1
    }
  done
}

@test "all agents have Context section" {
  for dept in "${DEPTS[@]}"; do
    for role in "${ROLES[@]}"; do
      OUTPUT=$(bash "$GENERATE" --role "$role" --dept "$dept" --dry-run 2>/dev/null)
      echo "$OUTPUT" | grep -q "## Context" || {
        echo "FAIL: ${dept}/${role} missing Context section"
        return 1
      }
    done
  done
}
